---
title: "Data Import Activity"
author: "Bastola"
date: "`r format(Sys.Date(), ' %B %d %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      collapse = TRUE, 
                      comment=NA, 
                      warning = FALSE,
                      message = FALSE,
                      fig.height = 4, fig.width = 6, fig.align='center')



library(tidyverse) 
library(tidyr)
library(forcats)
library(readr)
```


## Your turn 1

Use `read_csv()` to import the `desserts` data set from

https://raw.githubusercontent.com/deepbas/statdatasets/main/desserts.csv

```{r}
url <- " "
desserts <- read_csv()
glimpse(desserts)
```


```{r, eval=FALSE}
tmp_filename <- tempfile()
download.file(url, tmp_filename)
desserts1 <- read_csv(tmp_filename)
file.remove(tmp_filename)
glimpse(desserts1)
```


---------------------------------------------

## Your turn 2

Use the appropriate `read_<type>()` function to import the following data sets:

- `https://deepbas.io/data/simple-1.dat`

- `https://deepbas.io/data/mild-1.csv`

- `https://deepbas.io/data/tricky-1.csv`

If you hit any errors/problems, be sure to explore them and identify the issue, even if you can't "fix" it.


```{r}
simple1 <- readr::read_csv(" ")
```

```{r}
mild1 <- readr::read_delim(" ")
```

```{r}
tricky1 <-  read_csv(" ")
problems(tricky1)

```


```{r}
# fix it!


```



## Your Turn 3

```{r}
# import gss_cat dataset from forcats library
forcats::gss_cat
```


```{r}
gss_cat %>%
  drop_na(_____) %>%
  group_by(______) %>%
  summarize(tvhours = mean(_____)) %>%
  ggplot(aes(tvhours, fct_reorder(____, _______))) +
    geom_point()
```


```{r}
gss_cat %>%
  drop_na(______) %>%
  group_by(______) %>%
  summarize(tvhours = mean(______)) %>%
  ggplot(aes(tvhours, fct_reorder(_______,______))) +
    geom_point()

```

## Your Turn 4

```{r}
rincome_summary <- gss_cat %>%
  group_by(rincome) %>%
  summarize(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )
rincome_summary %>% ggplot(aes(age, fct_reorder(_____, _____))) +
    geom_point()+
    labs(y = "income")
  
```


## Your Turn 5

```{r}
gss_cat %>%
  drop_na(tvhours) %>%
  select(marital, tvhours) %>%
  mutate(
    maritalStatus =
      fct_collapse(
        )
  )

```




